channels:
- conda-forge
- defaults
dependencies:
  - pip:
      - alabaster==0.7.12
      - babel==2.8.0
      - category-encoders==2.2.2
      - chardet==3.0.4
      - cycler==0.10.0
      - dataclasses==0.6
      - dill==0.3.3
      - docutils==0.16
      - future==0.18.2
      - gensim==3.8.3
      - idna==2.10
      - imagesize==1.2.0
      - jinja2==2.11.2
      - joblib==0.17.0
      - kiwisolver==1.3.1
      - markupsafe==1.1.1
      - matplotlib==3.3.2
      - numpy==1.19.4
      - pandas==1.1.4
      - patsy==0.5.1
      - pillow==8.0.1
      - pygments==2.7.2
      - python-dateutil==2.8.1
      - pytz==2020.4
      - qregpy==1.1.1
      - requests==2.24.0
      - scikit-learn==0.23.2
      - scipy==1.5.4
      - smart-open==3.0.0
      - snowballstemmer==2.0.0
      - sphinx==3.3.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==1.0.3
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.4
      - sqlparse==0.4.1
      - statsmodels==0.12.1
      - threadpoolctl==2.1.0
      - torch==1.7.0
      - typing-extensions==3.7.4.3
      - urllib3==1.25.11
      - xgboost==1.2.1
name: etriml_env
